name: jenkins-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        uses: chuanqi129/build-jenkins-job@master
        with:
          jenkins-url: http://3.90.82.245:8080/
          job-path: job/aws_jenkins_job
          user: chuanqiw
          jenkins-token: ${{ secrets.AWS_JENKINS }}
#       - name: Get job status
#           run: echo "Job status is ${{ steps.job-build.outputs.job_status }}"
